<h1>Dashboard Admin Index</h1>

<div class="row">
  <!-- Navigation Buttons -->  
  <ul class="nav nav-tabs" id="myTabs">
    <li class="active"><a href="#home"><i class="pink icon-dashboard"></i>Home</a></li>
    <li><a href="#profile">Profile</a></li>
    <li><a href="#messages">Messages</a></li>
  </ul>

  <!-- Content -->  
  <div class="tab-content">
    <div class="tab-pane active" id="home"><h2>Home</h2></div>
    <div class="tab-pane" id="profile"><h2>Profile</h2></div>
    <div class="tab-pane" id="messages"><h2>Messages</h2></div>
  </div>
</div>