<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>
<h3>This is your project's main page</h3>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>URL KEY</th>
            <th>Status</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->rows as $page): ?>
        <tr>
            <td><?php echo $page->page_name; ?>
            <td><?php echo $page->url_key;  ?></td>
            <td><?php echo $page->page_status;  ?></td>
            <td>
                <a href="<?php echo $page->url_key; ?>">View Page</a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

<div id="more-information">
    <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
    <p>
        Helpful Links: <br />
        <a href="http://framework.zend.com/">Zend Framework Website</a> |
        <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
    </p>
</div>