<?php
function genMenu($container)
{
    $html ='';
    foreach ($container as $page)
    {
        $href = $page->uri;
        $target = '_self';
        $dropdown = !empty($page->pages);
     
        // check for subpages
        // if exists, insert a dropdown class and a data-toggle attribute
        // if not exists, let the <li>-attribute and <a>-attribute empty
        if (count($page->pages) > 0)
        {
            // li-element with subpages
            echo '<li' . ($dropdown ? ' class="dropdown"' : '') . '>';
            echo '<a href="' . ($dropdown ? '#' : $page->getHref()) . '"' . 'class="dropdown-toggle ' . $page->class . '" data-toggle="dropdown">';
            
            echo $page->getLabel();
            if ($dropdown) {
                echo '<b class="caret"></b>';
            }     
            echo '</a>';
        } else {            
            // li-element without subpages
            if($page->header) {
                echo '<li class="' . $page->header . '">';
                echo $page->getLabel();
            } else {
                echo '<li>';
                echo '<a href="' . $page->getHref() . '" class="' . $page->class . '">';
                echo $page->getLabel();
                echo '</a>'; 
            }    
        }

         //Add Image
        if(isset($page->img))
        {
            echo '<img src="path/' . $page->img . '">';
        }
        
        // Add Divider
        if(isset($page->divider))
        {
            echo '<li class="divider"></li>';
        }

        //Add Sub-itens
        if (!empty($page->pages))
        {
            echo '<ul class="dropdown-menu">';;
            genMenu($page->pages);
            echo '</ul>';
        }
    }
}
echo '<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">';
echo'<ul class="nav navbar-nav">';
genMenu($this->container);
echo'</ul>';
echo '</div>';