<?php
$arr = array(		
		'description' => 'My Application description meta',
		'keywords'    => 'framework, PHP, productivity'
		);
foreach ($arr as $key => $content) $this->headMeta()->appendName($key, $content);
?>
<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
		<?php echo $this->headTitle('Admin'); ?>
	    <?php echo $this->headMeta(); ?>
	    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/admin/styles.css')); ?>
	    <?php echo $this->headScript()->appendFile($this->baseUrl('js/admin/main.js')); ?>
	    <?php
echo $this->navigation()->breadcrumbs()?>
    </head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
				    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				      <span class="sr-only">Toggle navigation</span>
				      <span class="icon-bar"></span>
				      <span class="icon-bar"></span>
				      <span class="icon-bar"></span>
				    </button>
				    <a class="navbar-brand" href="/">Brand</a>
			  	</div>
				<?php
				/* Navigation Menu Itens */
				$this->navigation()->menu()->setPartial('partials/horizontal.phtml');
				echo $this->navigation()->menu()->render(Zend_Registry::get('admin'));
				?>
			</div>
		</nav>
		<div class="container">
			<?php echo $this->layout()->content; ?>
			<!-- Footer Links -->
			<footer>
				<div class="row">
					<div class="col-md-6">
						<ul class="list-inline pull-left">
							<li>Extremely Modular Application &copy; 2013</li>
							<li>
								<?php
								$getVersion = Bootstrap::getVersionInfo();
								echo $getVersion['major'].'.'.$getVersion['minor'].'.'.$getVersion['revision'];
								?>
							</li>
							<li><a href="#">Contact</a></li>
							<li><a href="#">About</a></li>
							<li><a href="#">Blog</a></li>
						</ul>
					</div>
      				<div class="col-md-6">
						<ul class="list-inline pull-right">
							<li><a href="#">Terms</a></li>
							<li><a href="#">Privaciy</a></li>
							<li><a href="#">Sucurity</a></li>
						</ul>
					</div>					
				</div>
			</footer>
		</div>
	</body>
</html>