<div class="page-header">
	<div class="row">
		<div class="col-md-6">
			<div class="pull-left">
				<h1>
					<?php
					// get the front controller instance
					$front = Zend_Controller_Front::getInstance();
					echo $front->getRequest()->getModuleName();
					echo ' '.$front->getRequest()->getControllerName();
					echo ' '.$front->getRequest()->getActionName();
					?>	
				</h1>
			</div>
		</div>
		<div class="col-md-6">
			<div class="pull-right">
				<a class="btn btn-success" href="<?php echo $this->url(array('module'=>'admin','controller'=>'content_pages','action'=>'new'),null,true); ?>">New Page</a>			
			</div>
		</div>
	</div>
</div>
<div class="row">
	<label>Per Page</label>
	<select name="" class="form-control">
		<option value="">10</option>
		<option value="">20</option>
	</select>	
</div>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Name</th>
			<th>URL KEY</th>
			<th>Status</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->rows as $page): ?>
		<tr>
			<td><?php echo $page->page_name; ?>
			<td><?php echo $page->url_key;  ?></td>
			<td>
			<?php if($page->page_status == 'enable') : ?>
				<span class="label label-success"><?php echo $page->page_status; ?></span>
			<?php else : ?>
				<span class="label label-warning"><?php echo $page->page_status; ?></span>
			<?php
				endif;
			?>
			</td>
			<td class="text-center">
				<a href="<?php echo $this->url(array('module'=>'admin','controller'=>'content_pages','action'=>'view','id'=>$page->id),null,true); ?>" class="decoration-none">
					<span class="label label-default">
						<i class="fa fa-eye"></i> View Page
					</span>
				</a>
				&nbsp;
				<a href="<?php echo $this->url(array('module'=>'admin','controller'=>'content_pages','action'=>'edit','id'=>$page->id),null,true); ?>" class="decoration-none">
					<span class="label label-primary">
						<i class="fa fa-pencil-square-o"></i>
					</span>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->rows, 'Elastic', array('controls.phtml', 'default')); ?>