<div class="page-header">
	<div class="row">
		<div class="col-md-6">
			<div class="pull-left">
				<h1>
					<?php
					// get the front controller instance
					$front = Zend_Controller_Front::getInstance();
					echo $front->getRequest()->getModuleName();
					echo ' '.$front->getRequest()->getControllerName();
					echo ' '.$front->getRequest()->getActionName();
					?>	
				</h1>
			</div>
		</div>
		<div class="col-md-6">
			<div class="pull-right">
				<a class="btn btn-primary" href="<?php echo $this->url(array('module'=>'admin','controller'=>'content_pages','action'=>'index'),null,true); ?>">Back</a>
				<a class="btn btn-primary" href="<?php echo $this->url(array('module'=>'admin','controller'=>'content_pages','action'=>'new'),null,true); ?>">New Page</a>				
			</div>
		</div>
	</div>
</div>
<span><strong>Add By</strong>: <?php echo $this->user->real_name; ?> in <em><?php echo new Zend_Date($this->content->page_created, null, 'pt_Br'); ?></em></span><br>
<span><strong>Last Update By</strong>: <?php echo $this->user->real_name; ?> in <em><?php echo new Zend_Date($this->content->page_update, null, 'pt_Br'); ?></em></span>
<h3><?php echo $this->content->page_name; ?></h3>
<?php
echo html_entity_decode($this->content->page_content,ENT_QUOTES,$this->charset);
?>
