<ul class="pagination">
<?php if ($this->pageCount): ?>
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <li>
    <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
      &laquo;
    </a>
  </li>
<?php else: ?>
  <li class="disabled"><a href="#">&laquo;</a></li>
<?php endif; ?>
 
<!-- Previous page link --
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>
-->
 
<!-- Next page link --
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Next &gt;</span> |
<?php endif; ?>
-->

<!-- Numbers Links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <li><a title="<?php echo $page; ?>" href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
    <?php else: ?>
        <li class="active"><a class="current" title="<?php echo $page; ?>" href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
    <?php endif; ?>
<?php endforeach; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <li>
    <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
      &raquo;
    </a>
  </li>
<?php else: ?>
  <li class="disabled"><a href="#">&raquo;</a></li>
<?php endif; ?>

<?php endif; ?>
</ul>